language: php

php:
    - 5.6
    - 7.0

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  - SYMFONY_VERSION=3.2.*

before_install:
  - composer self-update
  - composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update

install: composer update --prefer-source

script: phpunit --coverage-text
