app:
    resource: "@AppBundle/Controller/"
    type:     annotation

_security_login:
    pattern:  /login
    defaults: { _controller: AppBundle:Security:login }

_security_check:
    pattern:  /login_check

_security_logout:
    pattern:  /logout

_security_login_admin:
    pattern:  /admin/login
    defaults: { _controller: AdminBundle:Security:login }

_security_check_admin:
    pattern:  /admin/login_check

_security_logout_admin:
    pattern:  /admin/logout
