# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        CoreBundle\Entity\Admin:
            algorithm: bcrypt

        CoreBundle\Entity\User:
            algorithm: bcrypt

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        admin_provider:
            entity:
                class: CoreBundle:Admin
                property: email

        user_provider:
            entity:
                class: CoreBundle:User
                property: email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|bundles|images|scripts|styles|vednor)/
            security: false

        main:
            pattern: ^/

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            form_login:
                provider: user_provider
                login_path: /login
                check_path: /login_check

            logout:
                path:   /logout
                target: /

        admin:

        admin:
            pattern: ^/admin

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            form_login:
                provider: admin_provider
                login_path: /admin/login
                check_path: /admin/login_check

            logout:
                path:   /admin/logout
                target: /admin

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }