# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        CoreBundle\Entity\Admin:
            algorithm: bcrypt
            cost: 13

        CoreBundle\Entity\User:
            algorithm: bcrypt
            cost: 13

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        user_provider:
            entity:
                class: CoreBundle\Entity\User
                property: email

        admin_provider:
            entity:
                class: CoreBundle\Entity\Admin
                property: email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|bundles|images|scripts|styles|vendor)/
            security: false

        admin:
            pattern: ^/admin
            anonymous: ~

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            form_login:
                provider: admin_provider
                login_path: /admin/login
                check_path: /admin/login
                username_parameter: email
                password_parameter: password
                csrf_token_generator: security.csrf.token_manager

            logout:
                path:   /admin/logout
                target: /admin
                invalidate_session: false

        main:
            pattern: ^/
            anonymous: ~

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            form_login:
                provider: user_provider
                login_path: /login
                check_path: /login
                username_parameter: email
                password_parameter: password
                csrf_token_generator: security.csrf.token_manager

            logout:
                path:   /logout
                target: /
                invalidate_session: false

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/, role: ROLE_USER }
