services:
    workbook.app_twig_extension:
        class: AppBundle\Twig\TwigExtension
        public: false
        tags:
            - { name: twig.extension }
        arguments:
            - "@form.factory"
            - "@security.token_storage"
